/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-11-16 03:09:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.mangdog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import gang.DAOmangdog;
import gang.DTOmangdog;

public final class ad_005fmang_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("gang.DAOmangdog");
    _jspx_imports_classes.add("gang.DTOmangdog");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("  .card-footer{text-align: left;}\r\n");
      out.write("  .card-img-top{height: 300px; padding: 8px;}\r\n");
      out.write("  .card{ font-size: 12px; }\r\n");
      out.write("  .container1{ position: relative; width: 250px; height: 350px; margin: 60px auto;}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- 페이징 -->\r\n");
 
	int pageSize = 8;

	String pageNum = request.getParameter("pageNum");
	if (pageNum == null){ // 클릭한게 없으면 1번 페이지
	pageNum = "1";
	}

	int currentPage = Integer.parseInt(pageNum);

	int startRow = (currentPage - 1) * pageSize + 1;
	int endRow = currentPage * pageSize;

	int count = 0;
	DAOmangdog manager = DAOmangdog.getInstance();
	count = manager.getCount();


	List<DTOmangdog> mangList = null;
	if (count > 0) {
		// getList()메서드 호출 / 해당 레코드 반환
		mangList = manager.DTOmangList(startRow, endRow);
	}


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  게시글  -->\r\n");
      out.write("<div class=\"row\" style=\"width: 80%; margin: auto;\">	\r\n");
      out.write("\r\n");

	if (count > 0) { // 데이터베이스에 데이터가 있으면
		int number = count - (currentPage - 1) * pageSize; // 글 번호 순번 
		for (int i = 0; i < mangList.size(); i++) {
		DTOmangdog dto = mangList.get(i); // 반환된 list에 담긴 참조값 할당

      out.write("\r\n");
      out.write("<div class=\"col\">\r\n");
      out.write("<div class=\"container1\">\r\n");
      out.write("<div class=\"card\" >\r\n");
      out.write("\r\n");
      out.write("  <!-- 썸네일 -->\r\n");
      out.write("  <form action=\"ad_mang_detail.jsp\">\r\n");
      out.write("  <input type=\"image\" src=\"../mang_img/");
      out.print(dto.getMang_pic_save());
      out.write("\" class=\"card-img-top\" > \r\n");
      out.write("  \r\n");
      out.write("  <!-- 제목 및 내용 -->\r\n");
      out.write("  <div class=\"card-body\">\r\n");
      out.write("  <h5 class=\"card-title\"> ");
      out.print(dto.getMang_title() );
      out.write(" </h5>\r\n");
      out.write("  <p class=\"card-text\"> ");
      out.print(dto.getMang_id() );
      out.write(" </p>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <!-- input값 넘기기 -->\r\n");
      out.write("\r\n");
      out.write("  <input type=\"hidden\" id=\"mang_code\" name=\"mang_code\" value=\"");
      out.print(dto.getMang_code());
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" id=\"mang_id\" name=\"mang_id\" value=\"");
      out.print(dto.getMang_id());
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" id=\"mang_title\" name=\"mang_title\" value=\"");
      out.print(dto.getMang_title());
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" id=\"mang_content\" name=\"mang_content\" value=\"");
      out.print(dto.getMang_content());
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" id=\"mang_date\" name=\"mang_date\" value=\"");
      out.print(dto.getMang_date());
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" id=\"mang_pic\" name=\"mang_pic\" value=\"");
      out.print(dto.getMang_pic());
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" id=\"mang_pic_save\" name=\"mang_pic_save\" value=\"");
      out.print(dto.getMang_pic_save());
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" id=\"mang_count\" name=\"mang_count\" value=\"");
      out.print(dto.getMang_count() );
      out.write("\">\r\n");
      out.write("  <input type=\"hidden\" id=\"mang_like\" name=\"mang_like\" value=\"");
      out.print(dto.getMang_like() );
      out.write("\">\r\n");
      out.write("  </div>\r\n");
      out.write("  </form>\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"card-footer\" >\r\n");
      out.write("        <small class=\"text-muted\">\r\n");
      out.write("        ");
      out.print(dto.getMang_date());
      out.write("   &nbsp;&nbsp;\r\n");
      out.write("        \r\n");
      out.write("        <span style=\"float: right;\">\r\n");
      out.write("        <span> <img src=\"../icon/count.png\" width=\"20px\" height=\"20px\" style=\"margin-right: 3px;\"> ");
      out.print(dto.getMang_count());
      out.write(" &nbsp; </span>  \r\n");
      out.write("        <span> <img src=\"../icon/heart_icon.png\" width=\"18px\" height=\"18px\" style=\"margin-right: 3px;\"> ");
      out.print(dto.getMang_like());
      out.write(" </span>\r\n");
      out.write("        </span>\r\n");
      out.write("        \r\n");
      out.write("        </small>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div> ");
}	} else { 
      out.write(" 게시글이 없음다 ");
} 
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("\r\n");
	// 페이징  처리
	if(count > 0){
		// 총 페이지의 수
		int pageCount = count / pageSize + (count%pageSize == 0 ? 0 : 1);
		
		
		// 한 페이지에 보여줄 페이지 블럭(링크) 수
		int pageBlock = 10;
		
		
		// 한 페이지에 보여줄 시작 및 끝 번호(예 : 1, 2, 3 ~ 10 / 11, 12, 13 ~ 20)
		int startPage = ((currentPage-1)/pageBlock)*pageBlock+1;
		int endPage = startPage + pageBlock - 1;
							
		// 마지막 페이지가 총 페이지 수 보다 크면 endPage를 pageCount로 할당
		if(endPage > pageCount){
			endPage = pageCount;}
							
		if(startPage > pageBlock){ // 페이지 블록수보다 startPage가 클경우 이전 링크 생성 
      out.write("\r\n");
      out.write("			<a href=\"ad_mangdog.jsp?pageNum=");
      out.print(startPage - 10);
      out.write("\">[이전]</a>	\r\n");
      out.write("	\r\n");
      out.write("		");
	} for(int i=startPage; i <= endPage; i++){ // 페이지 블록 번호
				if(i == currentPage){ // 현재 페이지에는 링크를 설정하지 않음   
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		[");
      out.print(i );
      out.write("]\r\n");
      out.write("		\r\n");
      out.write("		");
	}else{ // 현재 페이지가 아닌 경우 링크 설정	
      out.write("\r\n");
      out.write("				<a href=\"ad_mangdog.jsp?pageNum=");
      out.print(i);
      out.write("\"> &nbsp; [");
      out.print(i );
      out.write("] &nbsp; </a>\r\n");
      out.write("		\r\n");
      out.write("		");
	} } // for end
			if(endPage < pageCount){ // 현재 블록의 마지막 페이지보다 페이지 전체 블록수가 클경우 다음 링크 생성
		
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		<a href=\"ad_mangdog.jsp?pageNum=");
      out.print(startPage + 10 );
      out.write("\">[다음]</a>\r\n");
      out.write("	\r\n");
      out.write("		");
}} 
      out.write("\r\n");
      out.write(" \r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
