/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-11-16 02:41:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/layouts/header", Long.valueOf(1666660431223L));
    _jspx_dependants.put("/layouts/sectionJS", Long.valueOf(1660936916000L));
    _jspx_dependants.put("/layouts/headerCSS", Long.valueOf(1668434616714L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>주인없는 하늘아래</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS/JS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSmenu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSsection.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSbanner.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSStab.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSShelp.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSmangdog.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSeffect.css\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSShover.css\" >\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/css/swiper.min.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ì¹ í°í¸ ì¤ì  -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gaegu&family=Noto+Serif+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Hahmlet:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ë§ë ë°°ë// ì´ ìì ììë íìí js, css ë¥¼ ë§í¬ê±¸ì´ ì¬ì© -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/css/swiper.min.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jquery ì¤ì  -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  h1,nav{font-family:  'Gaegu' !important;}\r\n");
      out.write("  button {height: 80%;}\r\n");
      out.write("  table {font-family: 'Hahmlet', serif;\r\n");
      out.write("      font-size : 20px;}\r\n");
      out.write("</style>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSlogin.css\" >\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("<!-- 아이디/비밀번호 찾기 새 창 열기-->\r\n");
      out.write("  function idPop(){\r\n");
      out.write("    var idpopup = window.open('M_login/l_finduser.jsp', '아이디 찾기', 'width=500px,height=400px, scrollbars=yes');\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("  function pwPop(){\r\n");
      out.write("       var pwpopup = window.open('M_login/l_findpw.jsp', '비밀번호 찾기', 'width=500px,height=400px, scrollbars=yes');\r\n");
      out.write("  }\r\n");
      out.write("  \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- header -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!-- 상단 로고  -->\r\n");
      out.write("<h1 style=\"text-align: center;\"> <a href=\"main.jsp\"/> <img src=\"icon/logo.png\" width=\"100\" height=\"100\"> </h1>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!-- 로그인/회원가입/로그아웃/마이페이지  -->\r\n");
//1.한글처리, 파라미터 
request.setCharacterEncoding("UTF-8");
String id = (String) session.getAttribute("id");
String name = request.getParameter("name");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
 if (session.getAttribute("id") == null) { 
      out.write("\r\n");
      out.write(" <a href=\"login.jsp\"><div style=\"position:absolute; right:80px; top:80px;\">  로그인  | </div></a>\r\n");
      out.write(" <a href=\"l_newmember.jsp\"><div style=\"position:absolute; right:20px; top:80px;\">  회원가입 </div></a> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
 }else if(id != null){
	if(id.equals("admin")){ 
      out.write("\r\n");
      out.write("	 <script>location.href = \"admin/ad_main.jsp\"; </script>\r\n");
 } else { 
      out.write("\r\n");
      out.write("	<div style=\"position:absolute; right:20px; top:60px;\">  ");
      out.print(id);
      out.write(" 님 환영합니다 ! </div>\r\n");
      out.write("	 <a href=\"logout.jsp\"><div style=\"position:absolute; right:80px; top:80px;\">  로그아웃  | &nbsp;&nbsp; </div></a> \r\n");
      out.write(" 	 <a href=\"mypage.jsp\"><div style=\"position:absolute; right:20px; top:80px;\">  마이페이지 </div></a>\r\n");
} }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 메뉴 -->\r\n");
      out.write("<nav>\r\n");
      out.write("   <!-- 메뉴 버튼 디자인  -->\r\n");
      out.write("   <div class=\"menu-btn\" >\r\n");
      out.write("      <div class=\"line line__1\"></div>\r\n");
      out.write("      <div class=\"line line__2\"></div>\r\n");
      out.write("      <div class=\"line line__3\"></div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <ul class=\"nav-links\">\r\n");
      out.write("      <a href=\"center.jsp\"> <li class=\"link\"> 센터 소개 </li> </a>\r\n");
      out.write("      <a href=\"adopt.jsp\"> <li class=\"link\"> 입양 </li> </a>\r\n");
      out.write("	  <a href=\"volunteer.jsp\"> <li class=\"link\"> 봉사활동 </li> </a>\r\n");
      out.write("	  <a href=\"support.jsp\"> <li class=\"link\"> 후원 </li> </a>\r\n");
      out.write("	  <a href=\"hospital.jsp\"> <li class=\"link\"> 동물병원 </li> </a>\r\n");
      out.write("	  <a href=\"mangdog.jsp\"> <li class=\"link\"> MANGDOG CONTEST </li> </a>\r\n");
      out.write("	  <a href=\"withdog.jsp\"> <li class=\"link\"> WITH DOG </li> </a>    \r\n");
      out.write("	</ul>  	  \r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- 메뉴 JS 설정 -->\r\n");
      out.write("<script  src=\"JS/JSmenu.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- section --> \r\n");
      out.write("<section style=\"margin-top: -950px\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"panda\">\r\n");
      out.write("  <div class=\"ear\"></div>\r\n");
      out.write("  <div class=\"face\">\r\n");
      out.write("    <div class=\"eye-shade\"></div>\r\n");
      out.write("    <div class=\"eye-white\">\r\n");
      out.write("      <div class=\"eye-ball\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"eye-shade rgt\"></div>\r\n");
      out.write("    <div class=\"eye-white rgt\">\r\n");
      out.write("      <div class=\"eye-ball\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"nose\"></div>\r\n");
      out.write("    <div class=\"mouth\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"body\"> </div>\r\n");
      out.write("  <div class=\"foot\">\r\n");
      out.write("    <div class=\"finger\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"foot rgt\">\r\n");
      out.write("    <div class=\"finger\"></div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<form action=\"M_login/l_loginpro.jsp\" name = \"login\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"hand\"></div>\r\n");
      out.write("  <div class=\"hand rgt\"></div>\r\n");
      out.write("  <h1> LOGIN </h1>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <input required=\"required\" class=\"form-control\"  name=\"id\" />\r\n");
      out.write("    <label class=\"form-label\">	ID    </label>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"form-group\">\r\n");
      out.write("    <input id=\"password\" type=\"password\" required=\"required\" class=\"form-control\"  name=\"pw\" />\r\n");
      out.write("    <label class=\"form-label\">Password</label>\r\n");
      out.write("    <p class=\"alert\">Invalid Credentials..!!</p>\r\n");
      out.write("    <button class=\"btnL\" type=\"submit\" name=\"login\">Login </button>\r\n");
      out.write("  </div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<button type=\"button\"  onclick=\"idPop()\"> 아이디 찾기 </button>  &nbsp;\r\n");
      out.write("<button type=\"button\"  onclick=\"pwPop()\"> 비밀번호 찾기 </button>  &nbsp;\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("<br><br><br><br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("<!-- footer  -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layouts/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>\r\n");
      out.write("<script  src=\"JS/JStab.js\"></script>\r\n");
      out.write("<!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("  \r\n");
      out.write("<script  src=\"JS/JSlogin.js\"></script> \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
