/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-11-18 11:22:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import gang.DTOlikely;
import gang.DAOlikely;
import java.util.List;
import gang.DAOmangdog;
import gang.DTOmangdog;

public final class mangdog_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/../layouts/mangdogJS", Long.valueOf(1667870529500L));
    _jspx_dependants.put("/layouts/header", Long.valueOf(1666660431223L));
    _jspx_dependants.put("/layouts/sectionJS", Long.valueOf(1660936916000L));
    _jspx_dependants.put("/layouts/headerCSS", Long.valueOf(1668434616714L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("gang.DAOmangdog");
    _jspx_imports_classes.add("gang.DAOlikely");
    _jspx_imports_classes.add("gang.DTOmangdog");
    _jspx_imports_classes.add("gang.DTOlikely");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>주인없는 하늘아래</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS/JS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSmenu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSsection.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSbanner.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSStab.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSShelp.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSmangdog.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSeffect.css\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSShover.css\" >\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/css/swiper.min.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ì¹ í°í¸ ì¤ì  -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gaegu&family=Noto+Serif+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Hahmlet:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ë§ë ë°°ë// ì´ ìì ììë íìí js, css ë¥¼ ë§í¬ê±¸ì´ ì¬ì© -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/css/swiper.min.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jquery ì¤ì  -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  h1,nav{font-family:  'Gaegu' !important;}\r\n");
      out.write("  .card-footer{text-align: left;}\r\n");
      out.write("  .card-img-top{height: 300px; padding: 8px;}\r\n");
      out.write("  .card{ font-size: 12px; }\r\n");
      out.write("  .container1{ position: relative; width: 250px; height: 350px; margin: 60px auto;}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function mangPop(){\r\n");
      out.write("    var mangPop = window.open('https://i.postimg.cc/3rDBcSQ8/mangdog.png', '망독', 'width=700px,height=700px, scrollbars=yes');\r\n");
      out.write("  } \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!-- 상단 로고  -->\r\n");
      out.write("<h1 style=\"text-align: center;\"> <a href=\"main.jsp\"/> <img src=\"icon/logo.png\" width=\"100\" height=\"100\"> </h1>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!-- 로그인/회원가입/로그아웃/마이페이지  -->\r\n");
//1.한글처리, 파라미터 
request.setCharacterEncoding("UTF-8");
String id = (String) session.getAttribute("id");
String name = request.getParameter("name");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
 if (session.getAttribute("id") == null) { 
      out.write("\r\n");
      out.write(" <a href=\"login.jsp\"><div style=\"position:absolute; right:80px; top:80px;\">  로그인  | </div></a>\r\n");
      out.write(" <a href=\"l_newmember.jsp\"><div style=\"position:absolute; right:20px; top:80px;\">  회원가입 </div></a> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
 }else if(id != null){
	if(id.equals("admin")){ 
      out.write("\r\n");
      out.write("	 <script>location.href = \"admin/ad_main.jsp\"; </script>\r\n");
 } else { 
      out.write("\r\n");
      out.write("	<div style=\"position:absolute; right:20px; top:60px;\">  ");
      out.print(id);
      out.write(" 님 환영합니다 ! </div>\r\n");
      out.write("	 <a href=\"logout.jsp\"><div style=\"position:absolute; right:80px; top:80px;\">  로그아웃  | &nbsp;&nbsp; </div></a> \r\n");
      out.write(" 	 <a href=\"mypage.jsp\"><div style=\"position:absolute; right:20px; top:80px;\">  마이페이지 </div></a>\r\n");
} }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 메뉴 -->\r\n");
      out.write("<nav>\r\n");
      out.write("   <!-- 메뉴 버튼 디자인  -->\r\n");
      out.write("   <div class=\"menu-btn\" >\r\n");
      out.write("      <div class=\"line line__1\"></div>\r\n");
      out.write("      <div class=\"line line__2\"></div>\r\n");
      out.write("      <div class=\"line line__3\"></div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <ul class=\"nav-links\">\r\n");
      out.write("      <a href=\"center.jsp\"> <li class=\"link\"> 센터 소개 </li> </a>\r\n");
      out.write("      <a href=\"adopt.jsp\"> <li class=\"link\"> 입양 </li> </a>\r\n");
      out.write("	  <a href=\"volunteer.jsp\"> <li class=\"link\"> 봉사활동 </li> </a>\r\n");
      out.write("	  <a href=\"support.jsp\"> <li class=\"link\"> 후원 </li> </a>\r\n");
      out.write("	  <a href=\"hospital.jsp\"> <li class=\"link\"> 동물병원 </li> </a>\r\n");
      out.write("	  <a href=\"mangdog.jsp\"> <li class=\"link\"> MANGDOG CONTEST </li> </a>\r\n");
      out.write("	  <a href=\"withdog.jsp\"> <li class=\"link\"> WITH DOG </li> </a>    \r\n");
      out.write("	</ul>  	  \r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- 메뉴 JS 설정 -->\r\n");
      out.write("<script  src=\"JS/JSmenu.js\"></script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- section -->\r\n");
      out.write("<section style=\"margin-top: -950px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  망독 소개 버튼  -->\r\n");
      out.write("<div style=\"width: 70%; margin: auto;\">\r\n");
      out.write("<button type=\"button\" class=\"bounce btn btn-outline-secondary\" onclick=\"mangPop()\" style=\"float: left;\"> 망독 콘테스트란 ? </button>\r\n");
      out.write("</div><br><br>\r\n");
      out.write("\r\n");
      out.write("<br><br><br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  좋아요 순 인기글  -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"box-shadow rounded swiper-container\" style=\"width: 1200px;\">\r\n");
      out.write("   <div class=\"swiper-wrapper\">\r\n");
      out.write("   ");
 
   DAOmangdog dao = new DAOmangdog();
   List<DTOmangdog> mangL_List = dao.DTOmangL_List();
   
   
   for (DTOmangdog f : mangL_List) { 
   
      out.write("\r\n");
      out.write("     \r\n");
      out.write("      <div class=\"swiper-slide \">\r\n");
      out.write("      <form>\r\n");
      out.write("        <input type=\"hidden\" id=\"mang_code\" name=\"mang_code\" value=\"");
      out.print(f.getMang_code());
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" id=\"mang_id\" name=\"mang_id\" value=\"");
      out.print(f.getMang_id());
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" id=\"mang_title\" name=\"mang_title\" value=\"");
      out.print(f.getMang_title());
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" id=\"mang_content\" name=\"mang_content\" value=\"");
      out.print(f.getMang_content());
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" id=\"mang_date\" name=\"mang_date\" value=\"");
      out.print(f.getMang_date());
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" id=\"mang_pic\" name=\"mang_pic\" value=\"");
      out.print(f.getMang_pic());
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" id=\"mang_pic_save\" name=\"mang_pic_save\" value=\"");
      out.print(f.getMang_pic_save());
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" id=\"mang_count\" name=\"mang_count\" value=\"");
      out.print(f.getMang_count() );
      out.write("\">\r\n");
      out.write("        <input type=\"hidden\" id=\"mang_like\" name=\"mang_like\" value=\"");
      out.print(f.getMang_like());
      out.write("\">\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"position-relative\" style=\"z-index: 10;\">\r\n");
      out.write("      	<div class=\"position-absolute top-0 start-0\">  <img src=\"icon/best.png\" style=\"width: 50px; height: 50px;  box-shadow:0 0 0px\"> </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"hover14 column\">\r\n");
      out.write("	  	<figure> <input type=\"image\" src=\"mang_img/");
      out.print(f.getMang_pic_save());
      out.write("\" style=\"width:300px; height: 300px;\" formaction=\"m_detail.jsp\"> </figure>\r\n");
      out.write("	  </div>\r\n");
      out.write("	  \r\n");
      out.write("	  \r\n");
      out.write("	  \r\n");
      out.write("    </form> </div>\r\n");
} 
      out.write(" </div> </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 게시글 페이징  -->\r\n");
 
   int pageSize = 8;

   String pageNum = request.getParameter("pageNum");
   if (pageNum == null){ // 클릭한게 없으면 1번 페이지
   pageNum = "1";
   }

   int currentPage = Integer.parseInt(pageNum);

   int startRow = (currentPage - 1) * pageSize + 1;
   int endRow = currentPage * pageSize;

   int count = 0;
   DAOmangdog manager = DAOmangdog.getInstance();
   count = manager.getCount();


   List<DTOmangdog> mangList = null;
   if (count > 0) {
      // getList()메서드 호출 / 해당 레코드 반환
      mangList = manager.DTOmangList(startRow, endRow);
   }


      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--  게시글  -->\r\n");
      out.write("<div class=\"row\" style=\"width: 70%; margin: auto;\">   \r\n");
      out.write("\r\n");

   if (count > 0) { // 데이터베이스에 데이터가 있으면
      int number = count - (currentPage - 1) * pageSize; // 글 번호 순번 
      for (int i = 0; i < mangList.size(); i++) {
      DTOmangdog dto = mangList.get(i); // 반환된 list에 담긴 참조값 할당
      
      request.setCharacterEncoding("UTF-8");
	  String id1 = (String) session.getAttribute("id");

	  if (id1 == null) {

      out.write("\r\n");
      out.write("<div class=\"col\">\r\n");
      out.write("<div class=\"container1\">\r\n");
      out.write("<div class=\"card \" >\r\n");
      out.write("\r\n");
      out.write("  <!-- 썸네일 -->\r\n");
      out.write("  <form name=\"login\" class=\"hover07 column\">\r\n");
      out.write("  <figure><input type=\"image\" src=\"mang_img/");
      out.print(dto.getMang_pic_save());
      out.write("\" class=\"card-img-top\" > </figure>\r\n");
      out.write("  \r\n");
      out.write("  <!-- 제목 및 내용 -->\r\n");
      out.write("  <div class=\"card-body\">\r\n");
      out.write("  <h5 class=\"card-title\"> ");
      out.print(dto.getMang_title() );
      out.write(" </h5>\r\n");
      out.write("  <p class=\"card-text\"> ");
      out.print(dto.getMang_id() );
      out.write(" </p>\r\n");
      out.write("  </div>\r\n");
      out.write("  </form>\r\n");
      out.write("  <div class=\"card-footer\" >\r\n");
      out.write("        <small class=\"text-muted\">\r\n");
      out.write("        ");
      out.print(dto.getMang_date());
      out.write("   &nbsp;&nbsp;\r\n");
      out.write("        \r\n");
      out.write("        <span style=\"float: right;\">\r\n");
      out.write("        <span> <img src=\"icon/count.png\" width=\"20px\" height=\"20px\" style=\"margin-right: 3px;\"> ");
      out.print(dto.getMang_count());
      out.write(" &nbsp; </span>  \r\n");
      out.write("        <span> <img src=\"icon/heart_icon.png\" width=\"18px\" height=\"18px\" style=\"margin-right: 3px;\"> ");
      out.print(dto.getMang_like());
      out.write(" </span>\r\n");
      out.write("        </span>\r\n");
      out.write("        \r\n");
      out.write("        </small>\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
}else{
      out.write("\r\n");
      out.write("	<div class=\"col\">\r\n");
      out.write("	<div class=\"container1\">\r\n");
      out.write("	<div class=\"card \" >\r\n");
      out.write("\r\n");
      out.write("	  <!-- 썸네일 -->\r\n");
      out.write("	  <form action=\"m_detail.jsp\">\r\n");
      out.write("	  <figure><input type=\"image\" src=\"mang_img/");
      out.print(dto.getMang_pic_save());
      out.write("\" class=\"card-img-top\" > </figure>\r\n");
      out.write("	  \r\n");
      out.write("	  <!-- 제목 및 내용 -->\r\n");
      out.write("	  <div class=\"card-body\">\r\n");
      out.write("	  <h5 class=\"card-title\"> ");
      out.print(dto.getMang_title() );
      out.write(" </h5>\r\n");
      out.write("	  <p class=\"card-text\"> ");
      out.print(dto.getMang_id() );
      out.write(" </p>\r\n");
      out.write("	  \r\n");
      out.write("	  \r\n");
      out.write("	  <!-- input값 넘기기 -->\r\n");
      out.write("\r\n");
      out.write("	  <input type=\"hidden\" id=\"mang_code\" name=\"mang_code\" value=\"");
      out.print(dto.getMang_code());
      out.write("\">\r\n");
      out.write("	  <input type=\"hidden\" id=\"mang_id\" name=\"mang_id\" value=\"");
      out.print(dto.getMang_id());
      out.write("\">\r\n");
      out.write("	  <input type=\"hidden\" id=\"mang_title\" name=\"mang_title\" value=\"");
      out.print(dto.getMang_title());
      out.write("\">\r\n");
      out.write("	  <input type=\"hidden\" id=\"mang_content\" name=\"mang_content\" value=\"");
      out.print(dto.getMang_content());
      out.write("\">\r\n");
      out.write("	  <input type=\"hidden\" id=\"mang_date\" name=\"mang_date\" value=\"");
      out.print(dto.getMang_date());
      out.write("\">\r\n");
      out.write("	  <input type=\"hidden\" id=\"mang_pic\" name=\"mang_pic\" value=\"");
      out.print(dto.getMang_pic());
      out.write("\">\r\n");
      out.write("	  <input type=\"hidden\" id=\"mang_pic_save\" name=\"mang_pic_save\" value=\"");
      out.print(dto.getMang_pic_save());
      out.write("\">\r\n");
      out.write("	  <input type=\"hidden\" id=\"mang_count\" name=\"mang_count\" value=\"");
      out.print(dto.getMang_count() );
      out.write("\">\r\n");
      out.write("	  <input type=\"hidden\" id=\"mang_like\" name=\"mang_like\" value=\"");
      out.print(dto.getMang_like() );
      out.write("\">\r\n");
      out.write("	  </div>\r\n");
      out.write("	  </form>\r\n");
      out.write("	  \r\n");
      out.write("	  <div class=\"card-footer\" >\r\n");
      out.write("	        <small class=\"text-muted\">\r\n");
      out.write("	        ");
      out.print(dto.getMang_date());
      out.write("   &nbsp;&nbsp;\r\n");
      out.write("	        \r\n");
      out.write("	        <span style=\"float: right;\">\r\n");
      out.write("	        <span> <img src=\"icon/count.png\" width=\"20px\" height=\"20px\" style=\"margin-right: 3px;\"> ");
      out.print(dto.getMang_count());
      out.write(" &nbsp; </span>  \r\n");
      out.write("	        <span> <img src=\"icon/heart_icon.png\" width=\"18px\" height=\"18px\" style=\"margin-right: 3px;\"> ");
      out.print(dto.getMang_like());
      out.write(" </span>\r\n");
      out.write("	        </span>\r\n");
      out.write("	        \r\n");
      out.write("	        </small>\r\n");
      out.write("	  </div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	</div>	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
}}} else { 
      out.write(" 게시글이 없습니다. ");
} 
      out.write(" \r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<br><br><br><br>\r\n");
      out.write("\r\n");
      out.write("<!-- 작성 버튼  -->             \r\n");
      out.write("<div style=\"margin-left: 1200px;\">\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-outline-secondary\" onclick=\"location.href= 'm_insertform.jsp' \" >글 작성</button>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
   // 페이징  처리
   if(count > 0){
      // 총 페이지의 수
      int pageCount = count / pageSize + (count%pageSize == 0 ? 0 : 1);
      
      
      // 한 페이지에 보여줄 페이지 블럭(링크) 수
      int pageBlock = 10;
      
      
      // 한 페이지에 보여줄 시작 및 끝 번호(예 : 1, 2, 3 ~ 10 / 11, 12, 13 ~ 20)
      int startPage = ((currentPage-1)/pageBlock)*pageBlock+1;
      int endPage = startPage + pageBlock - 1;
                     
      // 마지막 페이지가 총 페이지 수 보다 크면 endPage를 pageCount로 할당
      if(endPage > pageCount){
         endPage = pageCount;}
                     
      if(startPage > pageBlock){ // 페이지 블록수보다 startPage가 클경우 이전 링크 생성 
      out.write("\r\n");
      out.write("         <a href=\"mangdog.jsp?pageNum=");
      out.print(startPage - 10);
      out.write("\">[이전]</a>   \r\n");
      out.write("   \r\n");
      out.write("      ");
   } for(int i=startPage; i <= endPage; i++){ // 페이지 블록 번호
            if(i == currentPage){ // 현재 페이지에는 링크를 설정하지 않음   
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      [");
      out.print(i );
      out.write("]\r\n");
      out.write("      \r\n");
      out.write("      ");
   }else{ // 현재 페이지가 아닌 경우 링크 설정   
      out.write("\r\n");
      out.write("            <a href=\"mangdog.jsp?pageNum=");
      out.print(i);
      out.write("\"> &nbsp; [");
      out.print(i );
      out.write("] &nbsp; </a>\r\n");
      out.write("      \r\n");
      out.write("      ");
   } } // for end
         if(endPage < pageCount){ // 현재 블록의 마지막 페이지보다 페이지 전체 블록수가 클경우 다음 링크 생성
      
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      <a href=\"mangdog.jsp?pageNum=");
      out.print(startPage + 10 );
      out.write("\">[다음]</a>\r\n");
      out.write("   \r\n");
      out.write("      ");
}} dao.close(); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section>   \r\n");
      out.write("\r\n");
      out.write("<!-- footer  -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layouts/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>\r\n");
      out.write("<script  src=\"JS/JStab.js\"></script>\r\n");
      out.write("<!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("new Swiper('.swiper-container', {\r\n");
      out.write("\r\n");
      out.write("   slidesPerView : 3, // ëìì ë³´ì¬ì¤ ì¬ë¼ì´ë ê°¯ì\r\n");
      out.write("   spaceBetween : 30, // ì¬ë¼ì´ëê° ê°ê²©\r\n");
      out.write("   slidesPerGroup : 3, // ê·¸ë£¹ì¼ë¡ ë¬¶ì ì, slidesPerView ì ê°ì ê°ì ì§ì íëê² ì¢ì\r\n");
      out.write("\r\n");
      out.write("   // ê·¸ë£¹ìê° ë§ì§ ìì ê²½ì° ë¹ì¹¸ì¼ë¡ ë©ì°ê¸°\r\n");
      out.write("   // 3ê°ê° ëìì¼ ëëë° 1ê°ë§ ìë¤ë©´ 2ê°ë ë¹ì¹¸ì¼ë¡ ì±ìì 3ê°ë¥¼ ë§ë¬\r\n");
      out.write("   loopFillGroupWithBlank : true,\r\n");
      out.write("\r\n");
      out.write("   loop : true, // ë¬´í ë°ë³µ\r\n");
      out.write("\r\n");
      out.write("   pagination : { // íì´ì§\r\n");
      out.write("      el : '.swiper-pagination',\r\n");
      out.write("      clickable : true, // íì´ì§ì í´ë¦­íë©´ í´ë¹ ìì­ì¼ë¡ ì´ë, íìì ì§ì í´ ì¤ì¼ ê¸°ë¥ ìë\r\n");
      out.write("   },\r\n");
      out.write("   navigation : { // ë¤ë¹ê²ì´ì\r\n");
      out.write("      nextEl : '.swiper-button-next', // ë¤ì ë²í¼ í´ëì¤ëª\r\n");
      out.write("      prevEl : '.swiper-button-prev', // ì´ë² ë²í¼ í´ëì¤ëª\r\n");
      out.write("   },\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
