/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-11-16 02:44:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class support_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/layouts/header", Long.valueOf(1666660431223L));
    _jspx_dependants.put("/layouts/sectionJS", Long.valueOf(1660936916000L));
    _jspx_dependants.put("/layouts/headerCSS", Long.valueOf(1668434616714L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>주인없는 하늘아래</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS/JS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSmenu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSsection.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSbanner.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSStab.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSShelp.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSmangdog.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSeffect.css\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSShover.css\" >\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/css/swiper.min.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ì¹ í°í¸ ì¤ì  -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gaegu&family=Noto+Serif+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Hahmlet:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ë§ë ë°°ë// ì´ ìì ììë íìí js, css ë¥¼ ë§í¬ê±¸ì´ ì¬ì© -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/css/swiper.min.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jquery ì¤ì  -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("  h1,nav{ font-family:  'Gaegu' !important;}\r\n");
      out.write("  \r\n");
      out.write("  #b1{position:absolute; top:190px; left: 190px;}\r\n");
      out.write("  #b2{position:absolute; top:190px; left: 870px;}\r\n");
      out.write("  #b3{position:absolute; bottom:180px; left: 190px;}\r\n");
      out.write("  #b4{position:absolute; bottom:180px; left: 870px;}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- header -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!-- 상단 로고  -->\r\n");
      out.write("<h1 style=\"text-align: center;\"> <a href=\"main.jsp\"/> <img src=\"icon/logo.png\" width=\"100\" height=\"100\"> </h1>\r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write(" \r\n");
      out.write("<!-- 로그인/회원가입/로그아웃/마이페이지  -->\r\n");
//1.한글처리, 파라미터 
request.setCharacterEncoding("UTF-8");
String id = (String) session.getAttribute("id");
String name = request.getParameter("name");

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
 if (session.getAttribute("id") == null) { 
      out.write("\r\n");
      out.write(" <a href=\"login.jsp\"><div style=\"position:absolute; right:80px; top:80px;\">  로그인  | </div></a>\r\n");
      out.write(" <a href=\"l_newmember.jsp\"><div style=\"position:absolute; right:20px; top:80px;\">  회원가입 </div></a> \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
 }else if(id != null){
	if(id.equals("admin")){ 
      out.write("\r\n");
      out.write("	 <script>location.href = \"admin/ad_main.jsp\"; </script>\r\n");
 } else { 
      out.write("\r\n");
      out.write("	<div style=\"position:absolute; right:20px; top:60px;\">  ");
      out.print(id);
      out.write(" 님 환영합니다 ! </div>\r\n");
      out.write("	 <a href=\"logout.jsp\"><div style=\"position:absolute; right:80px; top:80px;\">  로그아웃  | &nbsp;&nbsp; </div></a> \r\n");
      out.write(" 	 <a href=\"mypage.jsp\"><div style=\"position:absolute; right:20px; top:80px;\">  마이페이지 </div></a>\r\n");
} }
      out.write("\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 메뉴 -->\r\n");
      out.write("<nav>\r\n");
      out.write("   <!-- 메뉴 버튼 디자인  -->\r\n");
      out.write("   <div class=\"menu-btn\" >\r\n");
      out.write("      <div class=\"line line__1\"></div>\r\n");
      out.write("      <div class=\"line line__2\"></div>\r\n");
      out.write("      <div class=\"line line__3\"></div>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <ul class=\"nav-links\">\r\n");
      out.write("      <a href=\"center.jsp\"> <li class=\"link\"> 센터 소개 </li> </a>\r\n");
      out.write("      <a href=\"adopt.jsp\"> <li class=\"link\"> 입양 </li> </a>\r\n");
      out.write("	  <a href=\"volunteer.jsp\"> <li class=\"link\"> 봉사활동 </li> </a>\r\n");
      out.write("	  <a href=\"support.jsp\"> <li class=\"link\"> 후원 </li> </a>\r\n");
      out.write("	  <a href=\"hospital.jsp\"> <li class=\"link\"> 동물병원 </li> </a>\r\n");
      out.write("	  <a href=\"mangdog.jsp\"> <li class=\"link\"> MANGDOG CONTEST </li> </a>\r\n");
      out.write("	  <a href=\"withdog.jsp\"> <li class=\"link\"> WITH DOG </li> </a>    \r\n");
      out.write("	</ul>  	  \r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- 메뉴 JS 설정 -->\r\n");
      out.write("<script  src=\"JS/JSmenu.js\"></script>");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!-- section --> \r\n");
      out.write("<section style=\"margin-top: -950px;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 전체 컨테이너  -->\r\n");
      out.write("<div class=\"container overflow-hidden\" style=\"font-family: 'Hahmlet', serif; font-size: 18px;\">\r\n");
      out.write("  <div class=\"row gy-5\">\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("      <a target=\"_blank\" href=\"https://meridiani.co.kr/index.html\">\r\n");
      out.write("      <img src=\"s_img/merdi_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("       </a>\r\n");
      out.write("      <br><br>\r\n");
      out.write("- 총금액을 정산해 최소 10%를 현금후원 합니다.<br>\r\n");
      out.write("- 더욱 건강해지도록 좋은 사료를 추가후원 합니다.<br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/merdi_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/merdi_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/merdi_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/merdi_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("</div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("     <a target=\"_blank\" href=\"https://smartstore.naver.com/ojtbusan\r\n");
      out.write("\">\r\n");
      out.write("      <img src=\"s_img/mejong_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("<br><br>\r\n");
      out.write("\r\n");
      out.write("- 위안부, 유기동물 후원 및 가치있는 굿즈를 만듭니다.<br>\r\n");
      out.write("- 매 달 후원 시 내역 및 명단을 인스타그램에 공유합니다.<br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/mejong_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/mejong_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/mejong_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/mejong_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("       <a target=\"_blank\" href=\"https://https://smartstore.naver.com/forseasonsofday\r\n");
      out.write("\">\r\n");
      out.write("      <img src=\"s_img/sagejeal_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>\r\n");
      out.write("\r\n");
      out.write("- 물건 구매시 생기는 기부금은 “동물자유연대”에 기부합니다.<br>\r\n");
      out.write("- 구매시 발생하는 기부금은 모든 고객들이 인지 할 수 있도록 인스타그램에 내용과 영수증을 기재해 놓습니다.<br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/sagejeal_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/sagejeal_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/sagejeal_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/sagejeal_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("</div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("       <a target=\"_blank\" href=\"https://smartstore.naver.com/mer_ci\">\r\n");
      out.write("      <img src=\"s_img/mehsi_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>\r\n");
      out.write("- 유기동물 뿐만 아니라 백혈병, 소아암 등 아동후원기부도 실시합니다.<br>\r\n");
      out.write("- 수익금의 20%를 유기동물들을 위해 후원합니다. <br>\r\n");
      out.write("- 매 달 후원자 명단을 인스타그램에 공유합니다.<br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/mehsi_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/mehsi_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/mehsi_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/mehsi_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("       <a target=\"_blank\" href=\"https://smartstore.naver.com/saintvine12\">\r\n");
      out.write("      <img src=\"s_img/saintvine_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>\r\n");
      out.write("- 후원 내역은 공식 인스타그램, 혹은 홈페이지 내에 기재 합니다.<br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/saintvine_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/saintvine_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/saintvine_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/saintvine_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("       <a target=\"_blank\" href=\"https://smartstore.naver.com/dear__bijou\">\r\n");
      out.write("      <img src=\"s_img/dearbybejoo_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>\r\n");
      out.write("- 매월 고객들의 후원금을 정산하여 판매금액의 10%(제작비,배송비,수수료 제외)를 ‘행동하는 동물 사랑 단체’에 기부됩니다.<br>\r\n");
      out.write("- 사이트 내 상품들은 1:1 핸드메이드로 자체제작됩니다.<br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/dearbybejoo_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/dearbybejoo_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/dearbybejoo_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/dearbybejoo_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("      <a target=\"_blank\" href=\"https://https://smartstore.naver.com/accompany96\">\r\n");
      out.write("      <img src=\"s_img/dognism_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>\r\n");
      out.write("- 유기견 구조단체 꽃길 팀에서 운영하는 쇼핑몰입니다.<br>\r\n");
      out.write("- 판매수익금의 10%를 현금 기부 합니다 (순수익금 약 30~ 50% 기부)<br>\r\n");
      out.write("- 나머지 수익금의 전액을 사비를 추가하여 길고양이의 치료비와 사료비를 내고 있습니다. <br>\r\n");
      out.write("- 후원 내역은 공식 홈페이지 내에 기재합니다. <br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/dognism_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/dognism_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/dognism_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/dognism_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("      <a target=\"_blank\" href=\"https://smartstore.naver.com/wishpedia\">\r\n");
      out.write("      <img src=\"s_img/betterpresent_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>\r\n");
      out.write("- 판매 순수익금 10% 이상을 도움이 필요한 보호소에 매달 기부합니다.<br>\r\n");
      out.write("- 기부금 내역은 공식인스타에 기재합니다.<br>\r\n");
      out.write("- 매달 후기금 후기들은 홈페이지 제품 상세 내용에 올립니다. <br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/betterpresent_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/betterpresent_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/betterpresent_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/betterpresent_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("        <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("       <a target=\"_blank\" href=\"https://smartstore.naver.com/naumpharm\">\r\n");
      out.write("      <img src=\"s_img/gloomiz_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br> \r\n");
      out.write("- 매출액의 일부를 보호소에 기부합니다.<br>\r\n");
      out.write("- 글루미즈 공지에 기부인증서를 게시합니다.<br>\r\n");
      out.write("- 매달 후원금 전달 내용을 간단하게 제품 상세내용에 기재합니다. <br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/gloomiz_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/gloomiz_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/gloomiz_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/gloomiz_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("      <a target=\"_blank\" href=\"https://smartstore.naver.com/ribbonroe\">\r\n");
      out.write("      <img src=\"s_img/ROE_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br> \r\n");
      out.write("- 유기견,유기묘 뿐만 아니라 생활이 어려운 사람들을 위해 무료 급식소에 쌀을 기부합니다.<br>\r\n");
      out.write("- 판매 순수익의 50%를 기부합니다.<br> \r\n");
      out.write("- 매달 재정 및 기부보고를 공식 홈페이지 공지사항에 올립니다. <br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/ROE_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/ROE_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/ROE_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/ROE_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("      <a target=\"_blank\" href=\"https://smartstore.naver.com/donatio\">\r\n");
      out.write("      <img src=\"s_img/uviversum_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br> \r\n");
      out.write("- 순 수익금의 일부를 안락사하지 않는 유기동물 보호소 ‘유기견에게 사랑을 주세요’ 업체로 후원됩니다. <br>\r\n");
      out.write("- 우니베리숨 제품은 신진 예술가들의 작품으로 만들어집니다.<br>\r\n");
      out.write("- 각 제품들은 수작업으로 만들어집니다. <br>\r\n");
      out.write("- 환경 보호를 위해 최소한의 포장, 재사용이 가능한 더스트백에 담아 발송 합니다.<br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/uviversum_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/uviversum_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/uviversum_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/uviversum_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("       <a target=\"_blank\" href=\"https://smartstore.naver.com/misostp\">\r\n");
      out.write("      <img src=\"s_img/misojikim_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br> \r\n");
      out.write("- 수익금의 절반을 안락사를 시키지 않기 위해 지원을 받지 못하는 개인이 운영하는 유기견보호소에 사료, 연탄 등 필요물품으로 후원합니다.<br> \r\n");
      out.write("- 모든 팔찌는 손으로 수작업으로 만들어 판매합니다. <br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/misojikim_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/misojikim_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/misojikim_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/misojikim_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("     \r\n");
      out.write("       <a target=\"_blank\" href=\"https://smartstore.naver.com/jgmh\">\r\n");
      out.write("      <img src=\"s_img/jogemahan_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>  \r\n");
      out.write("- 동물권행동 카라와 함께 시행하는 쇼핑몰입니다. <br>\r\n");
      out.write("- 판매금액의 10%를 매 달 후원금으로 전달 합니다.<br>\r\n");
      out.write("- 후원내역과 후원자 명단은 매달 인스타그램에 공지합니다.<br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/jogemahan_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/jogemahan_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/jogemahan_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/jogemahan_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("       <a target=\"_blank\" href=\"https://smartstore.naver.com/es_shop_\">\r\n");
      out.write("      <img src=\"s_img/deroda_jogo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>  \r\n");
      out.write("- 순 수익금의 20%를 후원합니다.\r\n");
      out.write("- 후원금액은 병원비, 사료비, 보호소 공사 설치 모금등으로 사용합니다. \r\n");
      out.write("- 후원자명은 매달 5~10일에 공식인스타그램에 기제됩니다.\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/deroda_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/deroda_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/deroda_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/deroda_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("       <a target=\"_blank\" href=\"https://smartstore.naver.com/ppottuppttu\">\r\n");
      out.write("      <img src=\"s_img/bodubadu_logo.JPG\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>  \r\n");
      out.write("- 판매금액의 10%를 ‘한나네 보호소’로 후원합니다.<br>\r\n");
      out.write("- 후원자 명단과 물품은 매월 초 공식 인스타그램에 및 홈페이지에 기재합니다. <br>\r\n");
      out.write("- 모든 상품은 친환경 완충제에 포장해 나가며, 환경오염 방지에 힘쓰고 있습니다. <br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/bodubadu_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/bodubadu_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/bodubadu_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/bodubadu_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("      <a target=\"_blank\" href=\"https://smartstore.naver.com/recherche\">\r\n");
      out.write("      <img src=\"s_img/leshlesue_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>  \r\n");
      out.write("- 판매수익의 10%을 유기견, 유기묘에 기부합니다.<br>\r\n");
      out.write("- 유기견, 유기묘 뿐만 아니라 위안부 할머님들을 위한 제품도 판매합니다. <br>\r\n");
      out.write("- 기부 내용은 홈페이지 제품 상세에 기부증서를 기재합니다.<br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/leshlesue_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/leshlesue_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/leshlesue_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/leshlesue_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div> \r\n");
      out.write("</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3\">\r\n");
      out.write("      <a target=\"_blank\" href=\"https://smartstore.naver.com/aenik\">\r\n");
      out.write("      <img src=\"s_img/aenik_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>  \r\n");
      out.write("- 수익의 10%는 매달 용인시 동물보호협회에 후원합니다.<br>\r\n");
      out.write("- 매 달 첫째 주의 공식 인스타그램을 통해 기부명단과 기부금 영수증을 기재합니다. <br>\r\n");
      out.write("- 순 은 제품만 취급하는 실버 전문 업체에서 제품을 생산합니다.<br>\r\n");
      out.write("- 변색을 막아주는 개별 보관 파우치를 제공합니다.<br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/aenik_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/aenik_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/aenik_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("\r\n");
      out.write("      </div> \r\n");
      out.write(" </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("       <a target=\"_blank\" href=\"https://smartstore.naver.com/heelaser\">\r\n");
      out.write("      <img src=\"s_img/dadamongnag_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>  \r\n");
      out.write("- 매 달 판매금액의 최소 10%를 사성 유기동물 보호소를 통해 후원합니다. <br>\r\n");
      out.write("- 강아지 보호소 ‘행동하는동물사랑’을 통해 매 달 현금후원과 봉사를 실시합니다.<br>\r\n");
      out.write("- 매 달 후원영수증과 리스트는 공식 인스타그램에 기재합니다. <br>\r\n");
      out.write("- 모든 제품은 포장제 간소화로 실시해 환경보호에 힘쓰고 있습니다. <br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/dadamongnag_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/dadamongnag_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/dadamongnag_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/dadamongnag_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("       <a target=\"_blank\" href=\"http://papeff.com/index.html\">\r\n");
      out.write("      <img src=\"s_img/papefe_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>  \r\n");
      out.write("- 모든제품에 판매금액을 1% 기부합니다.<br>\r\n");
      out.write("- 유기, 반려동물의 입양,임보 환경이 나아지도록 노력하는 켐페인을 실시하고 있습니다.<br> \r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/papefe_1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/papefe_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/papefe_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/papefe_4.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("      <a target=\"_blank\" href=\"https://smartstore.naver.com/sha_ggu\">\r\n");
      out.write("      <img src=\"s_img/shaggushop_logo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br> \r\n");
      out.write("- 수익금의 10%를 기부합니다. <br>\r\n");
      out.write("- 후원, 수익금은 공식 인스타그램의 스토리로 기제합니다. <br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/shaggushop_1.jpeg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/shaggushop_2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/shaggushop_3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("\r\n");
      out.write("      </div> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("      <a target=\"_blank\" href=\"https://daily-unique.com/category/%EC%9C%A0%EA%B8%B0%EB%8F%99%EB%AC%BC%ED%9B%84%EC%9B%90/49/\">\r\n");
      out.write("      <img src=\"s_img/dailyuniqelogo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br> \r\n");
      out.write("- 판매금액의 10% 이상을 후원센터의 물품, 후원금으로 후원합니다.<br>\r\n");
      out.write("- ‘함께할개사랑할개’ 와 ‘경묘당’과 협업하는 쇼핑몰입니다.<br>\r\n");
      out.write("- 후원자명단과 후원내역은 공식인스타그램에 기재합니다. <br>\r\n");
      out.write("- 몇 제품의 디자인은 보호센터에서 직접 키우는 동물들을 보고 영감을 받아 그립니다. <br>\r\n");
      out.write("- 기프트케이스, 품질보증서, 브랜드 택을 기본 제공합니다. <br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/dailyuniqe1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/dailyuniqe2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/dailyuniqe3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("      <a target=\"_blank\" href=\"https://delixir.co.kr/index.html\">\r\n");
      out.write("      <img src=\"s_img/delixirlogo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br> \r\n");
      out.write("- 매달 판매수익의 10%를 유기동물보호소에 기부합니다. <br>\r\n");
      out.write("- 지속적으로 후원 라인을 런칭 및 판매하여 유기동물 감소에 힘을 씁니다. <br>\r\n");
      out.write("- 월 말 기부활동과 봉사활동을 통해 후원금이 잘 사용되고 있는지 확인합니다.  <br>\r\n");
      out.write("<div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/delixir1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/delixir2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/delixir3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("      <a target=\"_blank\" href=\"https://hoono.kr/volunteer\">\r\n");
      out.write("      <img src=\"s_img/hoonologo.jpg\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>  \r\n");
      out.write("- 만들어서 돕는 기부키트를 실시하여 소비자들이 키트 구매 후 완성된 제품을 유기동물 보호소로 전달하는 프로그램을 운영하고 있습니다.<br> \r\n");
      out.write("- 사용하지 않는 반려용품을 보호소로 전달하는 프로그램을 운영하고 있습니다. <br>\r\n");
      out.write("- 매 기부 현황은 매월 초 공식홈페이지에 기재합니다. <br>\r\n");
      out.write("      <div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/hoono1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/hoono2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/hoono3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"col-6\">\r\n");
      out.write("      <div class=\"p-3 \">\r\n");
      out.write("       <a target=\"_blank\" href=\"30DAYSTORE https://coconutstore.co.kr/STORE\">\r\n");
      out.write("      <img src=\"s_img/30daystorelogo.JPG\" class=\"img-fluid\">\r\n");
      out.write("      </a>\r\n");
      out.write("      <br><br>  \r\n");
      out.write("- 순 수익금을 30일마다 전액 후원합니다. ( 매달 새로운 상품들의 수익금을 전액 후원하고 다음달 새로운 상품이 출시되면 이번 달 전액 후원은 종료되는 시스템)<br>\r\n");
      out.write("- 각종 후원 및 증서는 공식 홈페이지에 기재합니다.<br>\r\n");
      out.write("   <div class=\"text-center\">\r\n");
      out.write("<img src=\"s_img/30daystore1.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/30daystore2.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("<img src=\"s_img/30daystore3.jpg\" class=\"img-thumbnail\">\r\n");
      out.write("      </div> \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</section> \r\n");
      out.write(" \r\n");
      out.write("<!-- footer  -->\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "layouts/footer.jsp", out, false);
      out.write('\r');
      out.write('\n');
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>\r\n");
      out.write("<script  src=\"JS/JStab.js\"></script>\r\n");
      out.write("<!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
