/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-11-16 02:42:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.M_005fwithdog;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import gang.DTOjust;
import java.util.List;
import gang.DAOjust;

public final class w_005fjust_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/M_withdog/../layouts/justJS", Long.valueOf(1668182084899L));
    _jspx_dependants.put("/M_withdog/../layouts/headerCSS", Long.valueOf(1668434616714L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("gang.DTOjust");
    _jspx_imports_classes.add("gang.DAOjust");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>주인없는 하늘아래</title>\r\n");
      out.write("\r\n");
      out.write("<!-- Required meta tags -->\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS -->\r\n");
      out.write("	<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<!-- CSS/JS -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSmenu.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSsection.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSbanner.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSStab.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSShelp.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSmangdog.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSSeffect.css\" >\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/CSShover.css\" >\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/css/swiper.min.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ì¹ í°í¸ ì¤ì  -->\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Gaegu&family=Noto+Serif+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Hahmlet:wght@300&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ë§ë ë°°ë// ì´ ìì ììë íìí js, css ë¥¼ ë§í¬ê±¸ì´ ì¬ì© -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/css/swiper.min.css\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/Swiper/4.5.1/js/swiper.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- jquery ì¤ì  -->\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.3.1.slim.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Option 1: Bootstrap Bundle with Popper -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("iframe { width: 330px; height: 250px; border-radius: 30px;}\r\n");
      out.write(".img_blog { width: 330px; height: 250px; border-radius: 30px;}\r\n");
      out.write("p{ font-family:  'Hahmlet', serif;\">\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"container-sm\">\r\n");
      out.write("<!-- help  -->\r\n");
      out.write("   <div class=\"help-tip\" style=\"margin-top: -50px; margin-right: -200px; z-index:2;\">\r\n");
      out.write("      <p>\r\n");
      out.write("      <b>just for you</b> 페이지는 저희 보호센터가 견주들에게 도움을 주고자 <br>\r\n");
      out.write("      동물병원이나 전문 훈련사 중심으로 업로드 된 '유튜브 영상'과 '블로그'를 엄선하여<br>\r\n");
      out.write("      제공하는 페이지입니다. <br><br>\r\n");
      out.write("      \r\n");
      out.write("      이 페이지의 게시물은 상시 업데이트 될 수 있습니다.\r\n");
      out.write("      </p>\r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ---------------------------------------- 유튜브 구역 ------------------------------------------>\r\n");
      out.write("<div style=\"position: relative; z-index: 1;\" style=\"border : 1px  solid #000000;\">\r\n");
      out.write("<div class=\"swiper-container\" >\r\n");
      out.write("<div class=\"swiper-wrapper\">\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
 
DAOjust dao = new DAOjust();
List<DTOjust> youList = dao.DTOyouList();
List<DTOjust> blogList = dao.DTOblogList();
dao.close();

for (DTOjust f : youList) { 
      out.write(" \r\n");
      out.write("     <div class=\"swiper-slide\">\r\n");
      out.write("     	 <iframe src=\"https://www.youtube.com/embed/");
      out.print(f.getYou_link() );
      out.write("\" \r\n");
      out.write("              title=\"YouTube video player\" allow=\"accelerometer;  clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen>\r\n");
      out.write("         </iframe>\r\n");
      out.write("     </div>\r\n");
      out.write(" ");
} 
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!-- 다음/이전 버튼 -->\r\n");
      out.write("<div class=\"swiper-button-next\"></div>\r\n");
      out.write("<div class=\"swiper-button-prev\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 페이징 -->\r\n");
      out.write("<div class=\"swiper-pagination\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("new Swiper('.swiper-container', {\r\n");
      out.write("\r\n");
      out.write("   slidesPerView : 3, \r\n");
      out.write("   spaceBetween : 30, \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   loop : true, \r\n");
      out.write("\r\n");
      out.write("   pagination : { \r\n");
      out.write("      el : '.swiper-pagination',\r\n");
      out.write("      clickable : true, \r\n");
      out.write("   },\r\n");
      out.write("   navigation : { // ë¤ë¹ê²ì´ì\r\n");
      out.write("      nextEl : '.swiper-button-next', \r\n");
      out.write("      prevEl : '.swiper-button-prev', \r\n");
      out.write("   },\r\n");
      out.write("});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ---------------------------------------- 블로그 구역 ----------------------------------------  -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"swiper-container\">\r\n");
      out.write("<div class=\"swiper-wrapper\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
for (DTOjust f : blogList) {	
      out.write("\r\n");
      out.write("	<div class=\"swiper-slide\">\r\n");
      out.write("		<a href=\"");
      out.print(f.getBlog_link());
      out.write("\" target=\"_blank\">\r\n");
      out.write("     		 <img src=\"blog_img/");
      out.print( f.getBlog_thumb_save() );
      out.write("\" class=\"img_blog\" > <br>\r\n");
      out.write("     		 <b> ");
      out.print( f.getBlog_title() );
      out.write(" </b>  \r\n");
      out.write("     	</a>\r\n");
      out.write("     </div>\r\n");
      out.write(" ");
} 
      out.write("    \r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 다음/이전 버튼 -->\r\n");
      out.write("<div class=\"swiper-button-next\"></div>\r\n");
      out.write("<div class=\"swiper-button-prev\"></div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 페이징 -->\r\n");
      out.write("<div class=\"swiper-pagination\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("new Swiper('.swiper-container', {\r\n");
      out.write("\r\n");
      out.write("   slidesPerView : 3, \r\n");
      out.write("   spaceBetween : 30, \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   loop : true, \r\n");
      out.write("\r\n");
      out.write("   pagination : { \r\n");
      out.write("      el : '.swiper-pagination',\r\n");
      out.write("      clickable : true, \r\n");
      out.write("   },\r\n");
      out.write("   navigation : { // ë¤ë¹ê²ì´ì\r\n");
      out.write("      nextEl : '.swiper-button-next', \r\n");
      out.write("      prevEl : '.swiper-button-prev', \r\n");
      out.write("   },\r\n");
      out.write("});\r\n");
      out.write("</script>");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
