/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-11-16 02:57:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.admin.adopt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import gang.DTOdog;
import gang.DAOdog;
import java.util.List;

public final class ad_005fadopt_005fbabylist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("gang.DTOdog");
    _jspx_imports_classes.add("gang.DAOdog");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>admin_주인없는 하늘아래</title>\r\n");
      out.write("<style>\r\n");
      out.write("  h1,nav{font-family:  'Gaegu' !important;}\r\n");
      out.write("  input {font-size: 15px;   margin-left: 10px}\r\n");
      out.write("  table {font-family: 'Hahmlet', serif; font-size: 15px;}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("function dog_update() {\r\n");
      out.write("return true;\r\n");
      out.write("}\r\n");
      out.write("function dog_delete(frm) {\r\n");
      out.write(" frm.action='adopt/ad_adopt_delete.jsp';\r\n");
      out.write(" frm.submit();\r\n");
      out.write(" return true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
  
	DAOdog dao = new DAOdog();
    List<DTOdog> dogLists = dao.DTOdogList();
    dao.close();
 
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <table class=\"table table-striped table-hover\" style=\"width: 100%;\" >\r\n");
      out.write("    <tr>\r\n");
      out.write("   	 <th>메인 사진</th> <th>상세 사진 </th> <th> 정보 </th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    ");
for (DTOdog f : dogLists) { 
      out.write("\r\n");
      out.write("    <tr>\r\n");
      out.write("    <td><img src=\"../dog_img/");
      out.print( f.getDog_main_save() );
      out.write("\"  width=\"250px\" height=\"350px\"/></td>\r\n");
      out.write("    <td><img src=\"../dog_img/");
      out.print( f.getDog_detail_save() );
      out.write("\"  width=\"250px\" height=\"350px\"/></td>\r\n");
      out.write("    \r\n");
      out.write("    <td style=\"text-align: left;\">  \r\n");
      out.write("    <form action=\"adopt/ad_adopt_update.jsp\" onsubmit=\"dog_update()\"> \r\n");
      out.write("      <table>\r\n");
      out.write("       		<tr>\r\n");
      out.write("       			<td>코드 :</td>\r\n");
      out.write("       			<td><input type=\"text\" id=\"dog_code\" name=\"dog_code\" value=\"");
      out.print( f.getDog_code() );
      out.write("\"readonly/></td>\r\n");
      out.write("       		</tr>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("          <tr>\r\n");
      out.write("       			<td> 이름 :</td>\r\n");
      out.write("       			<td><input type=\"text\" id=\"dog_name\" name=\"dog_name\" value=\"");
      out.print( f.getDog_name());
      out.write("\"required/></td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>나이 :</td>\r\n");
      out.write("       	  		<td><input type=\"number\" id=\"dog_age\" name=\"dog_age\" value=\"");
      out.print(f.getDog_age() );
      out.write("\"required/></td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>견종 :</td>\r\n");
      out.write("       	  		<td><input type=\"text\" id=\"dog_breed\" name=\"dog_breed\" value=\"");
      out.print( f.getDog_breed() );
      out.write("\"required/></td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>성별 :</td>\r\n");
      out.write("       	  		<td><input type=\"text\" id=\"dog_sex\" name=\"dog_sex\" value=\"");
      out.print( f.getDog_sex() );
      out.write("\"required/></td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>체중 :</td>\r\n");
      out.write("       	  		<td> <input type=\"text\" id=\"dog_weight\" name=\"dog_weight\" value=\"");
      out.print( f.getDog_weight() );
      out.write("\" required/></td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>성격 :</td>\r\n");
      out.write("       	  		<td><input type=\"text\" id=\"dog_character\" name=\"dog_character\" value=\"");
      out.print( f.getDog_character() );
      out.write("\" required/></td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>질병 : </td>\r\n");
      out.write("       	  		<td><input type=\"text\" id=\"dog_disease\" name=\"dog_disease\" value=\"");
      out.print( f.getDog_disease() );
      out.write("\" required/></td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>스토리 :</td>\r\n");
      out.write("       	  		<td> <input type=\"text\" id=\"dog_story\" name=\"dog_story\" value=\"");
      out.print( f.getDog_story() );
      out.write("\" required/></td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>중성화 : </td>\r\n");
      out.write("       	  		<td><input type=\"text\" id=\"dog_neutralization\" name=\"dog_neutralization\" value=\"");
      out.print( f.getDog_neutralization() );
      out.write("\" required/></td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>접종 : </td>\r\n");
      out.write("       	  		<td><input type=\"text\" id=\"dog_vaccination\" name=\"dog_vaccination\" value=\"");
      out.print( f.getDog_vaccination() );
      out.write("\" required/></td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>메인 원본 : </td>\r\n");
      out.write("       	  		<td>&nbsp;&nbsp;");
      out.print( f.getDog_main() );
      out.write("</td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>메인 저장 : </td>\r\n");
      out.write("       	  		<td>&nbsp;&nbsp; ");
      out.print( f.getDog_main_save() );
      out.write("</td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>상세 원본 : </td>\r\n");
      out.write("       	  		<td>&nbsp;&nbsp;");
      out.print( f.getDog_detail() );
      out.write("</td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       	  \r\n");
      out.write("       	  <tr>\r\n");
      out.write("       	  		<td>상세 저장 : </td>\r\n");
      out.write("       	  		<td>&nbsp;&nbsp;");
      out.print(f.getDog_detail_save() );
      out.write("</td>\r\n");
      out.write("       	  </tr>\r\n");
      out.write("       </table>\r\n");
      out.write("     \r\n");
      out.write("      <div style=\"float: right;\">\r\n");
      out.write("       <button type=\"submit\" class=\"btn btn-outline-secondary\" >수정</button>	\r\n");
      out.write("	   <button type=\"button\" class=\"btn btn-outline-secondary\" onclick=\"return dog_delete(this.form)\"> 삭제 </button>  \r\n");
      out.write("	  </div>\r\n");
      out.write("	  </form>\r\n");
      out.write("	  \r\n");
      out.write("       </td>\r\n");
      out.write("       </tr>\r\n");
      out.write("\r\n");
 } 
      out.write("\r\n");
      out.write("  </table>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
